export const SELECTOR_TYPES = {
    BRANDS: {
        GET_BRANDS : "GET_BRANDS",
        GET_BRANDS_FAILED: "GET_BRANDS_FAILED",
        GET_BRANDS_SUCCEDED: "GET_BRANDS_SUCCEDED"
    },
    MODELS: {
        GET_MODELS: "GET_MODELS",
        GET_MODELS_FAILED: "GET_MODELS_FAILED",
        GET_MODELS_SUCCEDED: "GET_MODELS_SUCCEDED"
    }
}